'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { HiArrowLeft, HiPlus, HiMinus } from 'react-icons/hi'
import Link from 'next/link'
import { v4 as uuidv4 } from 'uuid'
/* eslint-disable */
export default function AddInstructor() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    specialization: '',
    experience: '',
    qualification: '',
    bio: '',
    status: 'active' as 'active' | 'inactive',
    rating: 4.5,
    students: 0 // This will be auto-calculated
  })
  const [assignedCourses, setAssignedCourses] = useState<string[]>([])
  const [courses, setCourses] = useState<any[]>([])
  const [studentData, setStudentData] = useState<any[]>([])
  const [autoGeneratedPassword, setAutoGeneratedPassword] = useState('')

  // Load available courses and students
  useEffect(() => {
    const storedCourses = JSON.parse(localStorage.getItem('courses') || '[]')
    setCourses(storedCourses)
    
    const storedStudents = JSON.parse(localStorage.getItem('students') || '[]')
    setStudentData(storedStudents)
    
    // Generate initial password
    setAutoGeneratedPassword(generatePassword())
  }, [])

  // Generate random password (8 characters)
  const generatePassword = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%'
    let password = ''
    for (let i = 0; i < 8; i++) {
      password += chars.charAt(Math.floor(Math.random() * chars.length))
    }
    return password
  }

  // Calculate total students for selected courses
  const calculateTotalStudents = (courseIds: string[]) => {
    if (!courseIds.length || !studentData.length) return 0
    
    let totalStudents = 0
    courseIds.forEach(courseId => {
      const courseStudents = studentData.filter(student => 
        student.courseId === courseId || 
        student.enrolledCourses?.includes(courseId)
      )
      totalStudents += courseStudents.length
    })
    return totalStudents
  }

  // Get course students details
  const getCourseStudentsDetails = (courseIds: string[]) => {
    if (!courseIds.length || !studentData.length) return []
    
    const studentsList: any[] = []
    courseIds.forEach(courseId => {
      const courseStudents = studentData.filter(student => 
        student.courseId === courseId || 
        student.enrolledCourses?.includes(courseId)
      )
      courseStudents.forEach(student => {
        studentsList.push({
          studentId: student.id || student.cnic,
          name: `${student.firstName} ${student.lastName || ''}`,
          email: student.email,
          cnic: student.cnic,
          courseId: courseId
        })
      })
    })
    return studentsList
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: name === 'rating' ? parseFloat(value) || 0 : value
    }))
  }

  const toggleCourseAssignment = (courseId: string) => {
    const newAssignedCourses = assignedCourses.includes(courseId)
      ? assignedCourses.filter(id => id !== courseId)
      : [...assignedCourses, courseId]
    
    setAssignedCourses(newAssignedCourses)
    
    // Update student count automatically
    const totalStudents = calculateTotalStudents(newAssignedCourses)
    setFormData(prev => ({
      ...prev,
      students: totalStudents
    }))
  }

  // Email sending function - RETURNS PROMISE
  const sendInstructorCredentials = async (instructorData: any) => {
    try {
      // Prepare course details for email
      const courseDetails = assignedCourses.map((courseId: string) => {
        const course = courses.find(c => c.id === courseId)
        const courseStudents = studentData.filter(student => 
          student.courseId === courseId || 
          student.enrolledCourses?.includes(courseId)
        ).length
        
        return {
          id: courseId,
          name: course?.title || 'Unnamed Course',
          studentCount: courseStudents
        }
      })

      // This would be your actual API endpoint
      const response = await fetch('/api/send-instructor-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          to: instructorData.email,
          name: instructorData.name,
          email: instructorData.email,
          password: instructorData.password,
          courses: courseDetails,
          totalStudents: instructorData.students,
          loginUrl: `${window.location.origin}/lms/auth/login`
        })
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to send email')
      }

      const result = await response.json()
      return { success: true, data: result }

    } catch (error: any) {
      console.error('Error sending email:', error)
      return { 
        success: false, 
        error: error.message || 'Failed to send email' 
      }
    }
  }

  // Save instructor credentials to instructorUsers
  const saveInstructorCredentials = (instructorId: string, email: string, password: string) => {
    const instructorUser = {
      id: instructorId,
      email,
      password,
      role: 'instructor',
      name: formData.name,
      createdAt: new Date().toISOString(),
      status: 'active',
      lastLogin: null
    }

    // Get existing instructor users
    const existingInstructorUsers = JSON.parse(localStorage.getItem('instructorUsers') || '[]')
    
    // Check if email already exists
    const emailExists = existingInstructorUsers.some((user: any) => user.email === email)
    if (emailExists) {
      throw new Error('An instructor with this email already exists')
    }

    // Add new instructor user
    localStorage.setItem('instructorUsers', JSON.stringify([...existingInstructorUsers, instructorUser]))
    
    return instructorUser
  }

  // Save instructor to instructors list
  const saveInstructorToSystem = (instructorId: string) => {
    // Get course details
    const assignedCourseDetails = assignedCourses.map(courseId => {
      const course = courses.find(c => c.id === courseId)
      return {
        id: courseId,
        name: course?.title || 'Unnamed Course',
        duration: course?.duration,
        fee: course?.fee
      }
    })

    // Get student details for assigned courses
    const studentList = getCourseStudentsDetails(assignedCourses)

    // Create instructor object
    const newInstructor = {
      id: instructorId,
      ...formData,
      assignedCourses: assignedCourseDetails,
      assignedCourseIds: assignedCourses,
      studentsList: studentList,
      students: formData.students, // Auto-calculated
      createdAt: new Date().toISOString(),
      lastLogin: null
    }

    // Save instructor to localStorage
    const existingInstructors = JSON.parse(localStorage.getItem('instructors') || '[]')
    localStorage.setItem('instructors', JSON.stringify([...existingInstructors, newInstructor]))
    
    return newInstructor
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    // Validation
    if (!formData.name || !formData.email) {
      alert('Please fill in all required fields')
      return
    }
    
    if (!assignedCourses.length) {
      alert('Please assign at least one course to the instructor')
      return
    }

    setLoading(true)

    try {
      // Generate unique ID
      const instructorId = uuidv4()

      // Step 1: FIRST SEND EMAIL (don't save anything yet)
      const emailResult = await sendInstructorCredentials({
        id: instructorId,
        ...formData,
        password: autoGeneratedPassword,
        students: formData.students
      })

      // If email fails, show error and stop
      if (!emailResult.success) {
        throw new Error(`Failed to send email: ${emailResult.error}`)
      }

      // Step 2: ONLY AFTER EMAIL SUCCESS, save credentials
      const instructorUser = saveInstructorCredentials(
        instructorId, 
        formData.email, 
        autoGeneratedPassword
      )

      // Step 3: Save instructor to system
      const newInstructor = saveInstructorToSystem(instructorId)

      // Show success message
      alert(`
        Instructor added successfully!
        
        Details:
        - Name: ${newInstructor.name}
        - Email: ${newInstructor.email}
        - Password: ${autoGeneratedPassword}
        - Assigned Courses: ${assignedCourses.length}
        - Total Students: ${newInstructor.students}
        
        Credentials have been sent to ${newInstructor.email}
      `)

      // Redirect to instructors list
      router.push('/lms/Admin_Portal/instructors')

    } catch (error: any) {
      console.error('Error adding instructor:', error)
      alert(`Error: ${error.message}`)
    } finally {
      setLoading(false)
    }
  }

  // Regenerate password
  const handleRegeneratePassword = () => {
    setAutoGeneratedPassword(generatePassword())
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <Link
            href="/lms/Admin_Portal/instructors"
            className="inline-flex items-center text-gray-600 hover:text-purple-600 mb-2"
          >
            <HiArrowLeft className="w-5 h-5 mr-2" />
            Back to Instructors
          </Link>
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900">Add New Instructor</h1>
          <p className="text-gray-600 mt-2">Add a new instructor profile to the system</p>
        </div>
      </div>

      {/* Form */}
      <div className="bg-white rounded-xl shadow-md p-6">
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Personal Information */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Personal Information</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
                  Full Name *
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  required
                  value={formData.name}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="e.g., Dr. Sarah Johnson"
                />
              </div>

              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
                  Email Address *
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  required
                  value={formData.email}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="e.g., sarah@example.com"
                />
              </div>

              <div>
                <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-1">
                  Phone Number
                </label>
                <input
                  type="tel"
                  id="phone"
                  name="phone"
                  value={formData.phone}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="e.g., +1 234 567 8900"
                />
              </div>

              {/* Auto-generated Password Display */}
              <div>
                <div className="flex justify-between items-center mb-1">
                  <label className="block text-sm font-medium text-gray-700">
                    Auto-generated Password *
                  </label>
                  <button
                    type="button"
                    onClick={handleRegeneratePassword}
                    className="text-xs text-purple-600 hover:text-purple-800"
                  >
                    Regenerate
                  </button>
                </div>
                <div className="flex items-center space-x-2">
                  <input
                    type="text"
                    readOnly
                    value={autoGeneratedPassword}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg bg-gray-50 font-mono"
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1">
                  This password will be sent to the instructor's email
                </p>
              </div>
            </div>
          </div>

          {/* Professional Details */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Professional Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="qualification" className="block text-sm font-medium text-gray-700 mb-1">
                  Qualification *
                </label>
                <input
                  type="text"
                  id="qualification"
                  name="qualification"
                  required
                  value={formData.qualification}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="e.g., PhD in Computer Science"
                />
              </div>

              <div>
                <label htmlFor="specialization" className="block text-sm font-medium text-gray-700 mb-1">
                  Specialization *
                </label>
                <input
                  type="text"
                  id="specialization"
                  name="specialization"
                  required
                  value={formData.specialization}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="e.g., Web Development, Data Science"
                />
              </div>

              <div>
                <label htmlFor="experience" className="block text-sm font-medium text-gray-700 mb-1">
                  Experience *
                </label>
                <input
                  type="text"
                  id="experience"
                  name="experience"
                  required
                  value={formData.experience}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="e.g., 8 years"
                />
              </div>

              {/* Auto-calculated Students Field */}
              <div>
                <label htmlFor="students" className="block text-sm font-medium text-gray-700 mb-1">
                  Students in Selected Courses
                </label>
                <input
                  type="number"
                  id="students"
                  name="students"
                  readOnly
                  value={formData.students}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg bg-gray-50 cursor-not-allowed"
                />
                <p className="text-xs text-gray-500 mt-1">
                  {assignedCourses.length > 0 
                    ? `Auto-calculated from ${assignedCourses.length} selected course(s)` 
                    : 'Select courses to see student count'}
                </p>
              </div>
            </div>
          </div>

          {/* Rating */}
          <div className="md:w-1/2">
            <label htmlFor="rating" className="block text-sm font-medium text-gray-700 mb-1">
              Rating (1-5)
            </label>
            <input
              type="number"
              id="rating"
              name="rating"
              min="0"
              max="5"
              step="0.1"
              value={formData.rating}
              onChange={handleInputChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
              placeholder="e.g., 4.5"
            />
          </div>

          {/* Bio */}
          <div>
            <label htmlFor="bio" className="block text-sm font-medium text-gray-700 mb-1">
              Biography
            </label>
            <textarea
              id="bio"
              name="bio"
              rows={4}
              value={formData.bio}
              onChange={handleInputChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
              placeholder="Write a brief biography about the instructor..."
            />
          </div>

          {/* Course Assignment */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Course Assignment</h3>
            <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-sm text-blue-700">
                <strong>Note:</strong> Selecting courses will automatically calculate the number of enrolled students.
              </p>
            </div>
            
            {courses.length === 0 ? (
              <div className="text-center py-8 text-gray-500">
                No courses available. Please add courses first.
              </div>
            ) : (
              <>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {courses.map((course) => {
                    const courseStudents = studentData.filter(student => 
                      student.courseId === course.id || 
                      student.enrolledCourses?.includes(course.id)
                    ).length
                    
                    return (
                      <div
                        key={course.id}
                        onClick={() => toggleCourseAssignment(course.id)}
                        className={`p-4 border rounded-lg cursor-pointer transition-all ${
                          assignedCourses.includes(course.id)
                            ? 'border-purple-500 bg-purple-50'
                            : 'border-gray-300 hover:border-purple-300'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex-1">
                            <h4 className="font-medium text-gray-900">{course.title}</h4>
                            <p className="text-sm text-gray-600 mt-1">{course.awardingBody}</p>
                            <p className="text-xs text-gray-500 mt-1">
                              {courseStudents} student(s) enrolled
                            </p>
                          </div>
                          {assignedCourses.includes(course.id) ? (
                            <HiMinus className="w-5 h-5 text-purple-600" />
                          ) : (
                            <HiPlus className="w-5 h-5 text-gray-400" />
                          )}
                        </div>
                      </div>
                    )
                  })}
                </div>
                
                {assignedCourses.length > 0 && (
                  <div className="mt-4 p-3 bg-green-50 border border-green-200 rounded-lg">
                    <p className="text-sm text-green-700">
                      <strong>Summary:</strong> {assignedCourses.length} course(s) selected with{' '}
                      {formData.students} total student(s)
                    </p>
                  </div>
                )}
              </>
            )}
          </div>

          {/* Status */}
          <div className="md:w-1/2">
            <label htmlFor="status" className="block text-sm font-medium text-gray-700 mb-1">
              Status *
            </label>
            <select
              id="status"
              name="status"
              required
              value={formData.status}
              onChange={handleInputChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
            >
              <option value="active">Active</option>
              <option value="inactive">Inactive</option>
            </select>
          </div>

          {/* Submit Button */}
          <div className="pt-4 border-t border-gray-200">
            <div className="flex justify-end space-x-4">
              <Link
                href="/lms/Admin_Portal/instructors"
                className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors"
              >
                Cancel
              </Link>
              <button
                type="submit"
                disabled={loading || !formData.email || !formData.name || assignedCourses.length === 0}
                className="px-6 py-2 bg-gradient-to-r from-purple-600 to-purple-800 text-white rounded-lg hover:from-purple-700 hover:to-purple-900 transition-all shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? (
                  <span className="flex items-center">
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                    Sending Credentials...
                  </span>
                ) : (
                  'Add Instructor & Send Credentials'
                )}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}