'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { v4 as uuidv4 } from 'uuid'
import {
  ArrowLeft,
  Mail,
  Phone,
  Award,
  Briefcase,
  Star,
  BookOpen,
  RefreshCw,
  FileText,
  Key,
  UserPlus,
  User,
  Wrench,
  ShieldCheck,
  Flame as Fire
} from 'lucide-react'

// Brand Colors
const BRAND_COLORS = {
  darkNavy: '#0B1C3D',
  darkRoyalBlue: '#1E3A8A',
  deepRed: '#B11217',
  white: '#FFFFFF',
  lightGrey: '#F4F6F8',
  softGrey: '#E5E7EB',
  darkGrey: '#1F2933',
  teal: '#1FB6C9',
  brightRed: '#D32F2F'
}
/* eslint-disable */

// Default courses from your CoursesPage
const DEFAULT_COURSES = [
  {
    id: 'pipe-fitter',
    title: 'Pipe Fitter',
    category: 'Technical Training',
    description: 'Master industrial pipe fitting techniques with hands-on training on cutting, threading, and installation following international standards.',
    duration: '8 Weeks',
    students: 'Max 20 per batch',
    level: 'Beginner to Advanced',
    highlights: [
      'Learn pipe cutting, threading, and installation',
      'Blueprint reading and interpretation',
      'Pipe system design and layout',
      'Safety protocols and standards',
      'Hands-on workshop training',
      'Industry certification preparation'
    ],
    price: 'PKR 25,000',
    originalPrice: 'PKR 30,000',
    savings: 'Save PKR 5,000',
    featured: true,
    rating: 4.8,
    reviews: 124,
    image: "https://images.pexels.com/photos/6124242/pexels-photo-6124242.jpeg",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'safety-inspector',
    title: 'Safety Inspector',
    category: 'Safety Training',
    description: 'Professional safety inspection training for construction and industrial environments with OSHA certification preparation.',
    duration: '6 Weeks',
    students: 'Max 15 per batch',
    level: 'Intermediate',
    highlights: [
      'OSHA standards and regulations',
      'Site inspection methodologies',
      'Risk assessment techniques',
      'Safety documentation',
      'Emergency response planning',
      'Certification exam preparation'
    ],
    price: 'PKR 30,000',
    originalPrice: 'PKR 35,000',
    savings: 'Save PKR 5,000',
    featured: true,
    rating: 4.9,
    reviews: 89,
    image: "https://images.pexels.com/photos/34082713/pexels-photo-34082713.jpeg",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'welding',
    title: 'Professional Welding',
    category: 'Technical Training',
    description: 'Comprehensive welding training covering MIG, TIG, and Arc welding techniques for industrial applications.',
    duration: '10 Weeks',
    students: 'Max 12 per batch',
    level: 'Beginner to Professional',
    highlights: [
      'MIG, TIG, and Arc welding techniques',
      'Metal identification and preparation',
      'Weld quality inspection',
      'Safety equipment usage',
      'Industry-standard certification',
      'Portfolio development'
    ],
    price: 'PKR 35,000',
    originalPrice: 'PKR 40,000',
    savings: 'Save PKR 5,000',
    featured: true,
    rating: 4.7,
    reviews: 156,
    image: "https://images.pexels.com/photos/7650512/pexels-photo-7650512.jpeg",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
]

export default function AddInstructor() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [sendingEmail, setSendingEmail] = useState(false)
  const [courses, setCourses] = useState<any[]>([])
  const [loadingCourses, setLoadingCourses] = useState(true)
  
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    specialization: '',
    experience: '',
    qualification: '',
    bio: '',
    status: 'active' as 'active' | 'inactive',
    rating: 4.5
  })
  
  const [selectedCourseId, setSelectedCourseId] = useState('')
  const [autoGeneratedPassword, setAutoGeneratedPassword] = useState('')
  const [usingDefaultCourses, setUsingDefaultCourses] = useState(false)

  // Load available courses from LocalStorage or use defaults
  useEffect(() => {
    const loadCourses = () => {
      try {
        const storedCourses = localStorage.getItem('lms_courses')
        
        if (storedCourses) {
          const parsedCourses = JSON.parse(storedCourses)
          setCourses(parsedCourses)
          setUsingDefaultCourses(false)
          console.log('✅ Loaded courses from localStorage:', parsedCourses.length)
        } else {
          // No courses found - use default courses and save them to localStorage
          console.log('📚 No courses found in localStorage. Using default courses...')
          setCourses(DEFAULT_COURSES)
          setUsingDefaultCourses(true)
          
          // Save default courses to localStorage for future use
          localStorage.setItem('lms_courses', JSON.stringify(DEFAULT_COURSES))
          console.log('✅ Default courses saved to localStorage')
        }
      } catch (error) {
        console.error('❌ Error loading courses:', error)
        // Fallback to default courses on error
        setCourses(DEFAULT_COURSES)
        setUsingDefaultCourses(true)
      } finally {
        setLoadingCourses(false)
      }
    }

    loadCourses()
    generatePassword()
  }, [])

  // Generate random password (10 characters)
  const generatePassword = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%'
    let password = ''
    for (let i = 0; i < 10; i++) {
      password += chars.charAt(Math.floor(Math.random() * chars.length))
    }
    setAutoGeneratedPassword(password)
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: name === 'rating' ? parseFloat(value) || 0 : value
    }))
  }

  // Email sending function using your Gmail configuration
  const sendInstructorCredentials = async (instructorData: any, selectedCourse: any) => {
    try {
      const response = await fetch('/api/send-instructor-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          to: instructorData.email,
          instructorName: instructorData.name,
          email: instructorData.email,
          password: instructorData.password,
          courseName: selectedCourse?.title || 'Not Assigned',
          loginUrl: `${window.location.origin}/lms/auth/login?type=instructor`
        })
      })

      if (!response.ok) {
        throw new Error('Failed to send email')
      }

      const result = await response.json()
      return { success: true, data: result }

    } catch (error: any) {
      console.error('Error sending email:', error)
      return { 
        success: false, 
        error: error.message || 'Failed to send email credentials' 
      }
    }
  }

  // Save instructor credentials to LocalStorage (instructor_users)
  const saveInstructorCredentials = (instructorId: string, instructorData: any, password: string) => {
    const instructorUser = {
      id: instructorId,
      email: instructorData.email,
      password: password,
      role: 'instructor',
      name: instructorData.name,
      phone: instructorData.phone,
      createdAt: new Date().toISOString(),
      status: 'active',
      lastLogin: null,
      courseId: selectedCourseId
    }

    // Get existing instructor users
    const existingUsers = JSON.parse(localStorage.getItem('instructor_users') || '[]')
    
    // Check if email already exists
    const emailExists = existingUsers.some((user: any) => user.email === instructorData.email)
    if (emailExists) {
      throw new Error('An instructor with this email already exists')
    }

    // Add new instructor user
    const updatedUsers = [...existingUsers, instructorUser]
    localStorage.setItem('instructor_users', JSON.stringify(updatedUsers))
    
    return instructorUser
  }

  // Save instructor to instructors list
  const saveInstructorToSystem = (instructorId: string, selectedCourse: any) => {
    const selectedCourseDetails = selectedCourse ? {
      id: selectedCourse.id,
      title: selectedCourse.title,
      duration: selectedCourse.duration,
      category: selectedCourse.category,
      price: selectedCourse.price,
      students: selectedCourse.students
    } : null

    // Create instructor object
    const newInstructor = {
      id: instructorId,
      ...formData,
      assignedCourse: selectedCourseDetails,
      courseId: selectedCourseId,
      password: autoGeneratedPassword, // Store for reference
      totalStudents: selectedCourse?.students || 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }

    // Save instructor to localStorage
    const existingInstructors = JSON.parse(localStorage.getItem('lms_instructors') || '[]')
    const updatedInstructors = [...existingInstructors, newInstructor]
    localStorage.setItem('lms_instructors', JSON.stringify(updatedInstructors))
    
    return newInstructor
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    // Validation
    if (!formData.name || !formData.email) {
      alert('Please fill in all required fields')
      return
    }
    
    if (!selectedCourseId) {
      alert('Please select a course for the instructor')
      return
    }

    setLoading(true)
    setSendingEmail(true)

    try {
      // Get selected course details
      const selectedCourse = courses.find(c => c.id === selectedCourseId)
      
      // Step 1: FIRST send email (don't save anything yet)
      const emailResult = await sendInstructorCredentials({
        id: uuidv4(),
        ...formData,
        password: autoGeneratedPassword
      }, selectedCourse)

      // If email fails, show error and stop
      if (!emailResult.success) {
        throw new Error(`Failed to send email: ${emailResult.error}`)
      }

      // Step 2: ONLY AFTER EMAIL SUCCESS, generate ID and save data
      const instructorId = uuidv4()
      
      // Save credentials
      const instructorUser = saveInstructorCredentials(
        instructorId, 
        formData, 
        autoGeneratedPassword
      )

      // Save instructor to system
      const newInstructor = saveInstructorToSystem(instructorId, selectedCourse)

      // Show detailed success message
      alert(`
✅ Instructor Added Successfully!

Instructor Details:
• Name: ${newInstructor.name}
• Email: ${newInstructor.email}
• Course: ${selectedCourse?.title || 'Not assigned'}
• Status: ${newInstructor.status}

Login Credentials:
• Email: ${newInstructor.email}
• Password: ${autoGeneratedPassword}
• Login URL: ${window.location.origin}/lms/auth/login?type=instructor

✅ Credentials have been sent to ${newInstructor.email}
✅ Instructor can now login to the Instructor Portal
      `)

      // Redirect to instructors list
      router.push('/lms/Admin_Portal/instructors')

    } catch (error: any) {
      console.error('Error adding instructor:', error)
      alert(`❌ Error: ${error.message}`)
    } finally {
      setLoading(false)
      setSendingEmail(false)
    }
  }

  // Regenerate password
  const handleRegeneratePassword = () => {
    generatePassword()
  }

  // Get icon for course
  const getCourseIcon = (courseTitle: string) => {
    if (courseTitle === 'Pipe Fitter') return <Wrench className="w-4 h-4" style={{ color: BRAND_COLORS.darkRoyalBlue }} />
    if (courseTitle === 'Safety Inspector') return <ShieldCheck className="w-4 h-4" style={{ color: BRAND_COLORS.darkRoyalBlue }} />
    if (courseTitle === 'Professional Welding') return <Fire className="w-4 h-4" style={{ color: BRAND_COLORS.darkRoyalBlue }} />
    return <BookOpen className="w-4 h-4" style={{ color: BRAND_COLORS.darkRoyalBlue }} />
  }

  const selectedCourse = courses.find(c => c.id === selectedCourseId)

  return (
    <div className="min-h-screen bg-white p-6">
      {/* Header */}
      <div className="mb-8">
        <div className="bg-lightGrey rounded-xl p-6 border border-softGrey">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-4">
              <Link
                href="/lms/Admin_Portal/instructors"
                className="p-2 text-darkGrey hover:text-darkRoyalBlue hover:bg-white rounded-lg transition-colors"
              >
                <ArrowLeft className="w-5 h-5" />
              </Link>
              <div>
                <h1 className="text-2xl font-bold" style={{ color: BRAND_COLORS.darkRoyalBlue }}>
                  Add New Instructor
                </h1>
                <p className="text-darkGrey mt-1">
                  Add instructor and send login credentials via email
                </p>
              </div>
            </div>
            {usingDefaultCourses && (
              <span className="px-3 py-1.5 text-xs rounded-full bg-teal/10 text-teal border border-teal/20">
                Using Default Courses
              </span>
            )}
          </div>
          <div className="h-1 w-12 rounded-full" style={{ backgroundColor: BRAND_COLORS.deepRed }}></div>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="max-w-4xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Column - Personal Information */}
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white rounded-lg border border-softGrey p-6">
              <h2 className="text-lg font-semibold mb-4" style={{ color: BRAND_COLORS.darkNavy }}>
                Personal Information
              </h2>
              
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-darkGrey mb-2">
                      Full Name *
                    </label>
                    <div className="relative">
                      <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="text"
                        name="name"
                        required
                        value={formData.name}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                        placeholder="e.g., Dr. Sarah Johnson"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-darkGrey mb-2">
                      Email Address *
                    </label>
                    <div className="relative">
                      <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="email"
                        name="email"
                        required
                        value={formData.email}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                        placeholder="e.g., sarah@example.com"
                      />
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-darkGrey mb-2">
                      Phone Number
                    </label>
                    <div className="relative">
                      <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="tel"
                        name="phone"
                        value={formData.phone}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                        placeholder="e.g., +92 300 1234567"
                      />
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <label className="block text-sm font-medium text-darkGrey">
                        Auto-generated Password *
                      </label>
                      <button
                        type="button"
                        onClick={handleRegeneratePassword}
                        className="flex items-center gap-1 text-sm text-darkRoyalBlue hover:text-darkRoyalBlue/80"
                      >
                        <RefreshCw className="w-4 h-4" />
                        Regenerate
                      </button>
                    </div>
                    <div className="relative">
                      <Key className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="text"
                        readOnly
                        value={autoGeneratedPassword}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg bg-lightGrey font-mono"
                      />
                    </div>
                    <p className="text-xs text-darkGrey/70 mt-1">
                      This password will be sent to instructor's email
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Professional Details */}
            <div className="bg-white rounded-lg border border-softGrey p-6">
              <h2 className="text-lg font-semibold mb-4" style={{ color: BRAND_COLORS.darkNavy }}>
                Professional Details
              </h2>
              
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-darkGrey mb-2">
                      Qualification *
                    </label>
                    <div className="relative">
                      <Award className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="text"
                        name="qualification"
                        required
                        value={formData.qualification}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                        placeholder="e.g., PhD in Computer Science"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-darkGrey mb-2">
                      Specialization *
                    </label>
                    <div className="relative">
                      <Briefcase className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="text"
                        name="specialization"
                        required
                        value={formData.specialization}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                        placeholder="e.g., Web Development, Data Science"
                      />
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-darkGrey mb-2">
                      Experience *
                    </label>
                    <div className="relative">
                      <Briefcase className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="text"
                        name="experience"
                        required
                        value={formData.experience}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                        placeholder="e.g., 8 years"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-darkGrey mb-2">
                      Rating (1-5)
                    </label>
                    <div className="relative">
                      <Star className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                      <input
                        type="number"
                        name="rating"
                        min="0"
                        max="5"
                        step="0.1"
                        value={formData.rating}
                        onChange={handleInputChange}
                        className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Biography */}
            <div className="bg-white rounded-lg border border-softGrey p-6">
              <h2 className="text-lg font-semibold mb-4" style={{ color: BRAND_COLORS.darkNavy }}>
                Biography
              </h2>
              <div className="relative">
                <FileText className="absolute left-3 top-3 w-5 h-5 text-darkGrey/50" />
                <textarea
                  name="bio"
                  rows={4}
                  value={formData.bio}
                  onChange={handleInputChange}
                  className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20"
                  placeholder="Write a brief biography about the instructor..."
                />
              </div>
            </div>
          </div>

          {/* Right Column - Course Assignment & Status */}
          <div className="space-y-6">
            {/* Course Assignment */}
            <div className="bg-white rounded-lg border border-softGrey p-6">
              <h2 className="text-lg font-semibold mb-4" style={{ color: BRAND_COLORS.darkNavy }}>
                Course Assignment
              </h2>
              
              <div className="space-y-4">
                {loadingCourses ? (
                  <div className="text-center py-4">
                    <div className="inline-block animate-spin rounded-full h-6 w-6 border-2 border-gray-300 border-t-darkRoyalBlue"></div>
                    <p className="text-sm text-darkGrey mt-2">Loading courses...</p>
                  </div>
                ) : courses.length === 0 ? (
                  <div className="text-center py-4">
                    <BookOpen className="w-12 h-12 mx-auto mb-2" style={{ color: BRAND_COLORS.softGrey }} />
                    <p className="text-sm text-darkGrey">No courses available</p>
                    <p className="text-xs text-darkGrey/70 mt-1">
                      Add courses first to assign instructors
                    </p>
                  </div>
                ) : (
                  <>
                    <div>
                      <label className="block text-sm font-medium text-darkGrey mb-2">
                        Select Course *
                      </label>
                      <div className="relative">
                        <BookOpen className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-darkGrey/50" />
                        <select
                          value={selectedCourseId}
                          onChange={(e) => setSelectedCourseId(e.target.value)}
                          required
                          className="w-full pl-10 pr-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20 bg-white appearance-none"
                        >
                          <option value="">Select a course</option>
                          {courses.map(course => (
                            <option key={course.id} value={course.id}>
                              {course.title} ({course.category})
                            </option>
                          ))}
                        </select>
                      </div>
                    </div>

                    {selectedCourse && (
                      <div className="bg-lightGrey rounded-lg p-4 border border-softGrey">
                        <div className="flex items-center gap-2 mb-3">
                          <div className="p-1.5 rounded-lg" style={{ backgroundColor: `${BRAND_COLORS.darkRoyalBlue}10` }}>
                            {getCourseIcon(selectedCourse.title)}
                          </div>
                          <h4 className="font-medium text-darkGrey">{selectedCourse.title}</h4>
                        </div>
                        <div className="space-y-2">
                          <div className="flex items-center justify-between">
                            <span className="text-sm text-darkGrey/70">Category:</span>
                            <span className="text-sm text-darkGrey">{selectedCourse.category}</span>
                          </div>
                          <div className="flex items-center justify-between">
                            <span className="text-sm text-darkGrey/70">Duration:</span>
                            <span className="text-sm text-darkGrey">{selectedCourse.duration}</span>
                          </div>
                          <div className="flex items-center justify-between">
                            <span className="text-sm text-darkGrey/70">Students:</span>
                            <span className="text-sm text-darkGrey">{selectedCourse.students}</span>
                          </div>
                          <div className="flex items-center justify-between">
                            <span className="text-sm text-darkGrey/70">Price:</span>
                            <span className="text-sm font-medium" style={{ color: BRAND_COLORS.darkRoyalBlue }}>
                              {selectedCourse.price}
                            </span>
                          </div>
                        </div>
                      </div>
                    )}
                  </>
                )}
              </div>
            </div>

            {/* Status */}
            <div className="bg-white rounded-lg border border-softGrey p-6">
              <h2 className="text-lg font-semibold mb-4" style={{ color: BRAND_COLORS.darkNavy }}>
                Status & Settings
              </h2>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-darkGrey mb-2">
                    Status *
                  </label>
                  <select
                    name="status"
                    required
                    value={formData.status}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2.5 border border-softGrey rounded-lg focus:outline-none focus:border-darkRoyalBlue focus:ring-1 focus:ring-darkRoyalBlue/20 bg-white"
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                  </select>
                </div>

                <div className="bg-lightGrey rounded-lg p-4 border border-softGrey">
                  <h4 className="font-medium text-darkGrey mb-2">Process Summary</h4>
                  <ol className="text-sm text-darkGrey/70 space-y-2">
                    <li className="flex items-center gap-2">
                      <div className="w-5 h-5 rounded-full bg-lightGrey border border-softGrey flex items-center justify-center text-xs">
                        1
                      </div>
                      <span>Admin fills instructor details</span>
                    </li>
                    <li className="flex items-center gap-2">
                      <div className="w-5 h-5 rounded-full bg-lightGrey border border-softGrey flex items-center justify-center text-xs">
                        2
                      </div>
                      <span>System generates password</span>
                    </li>
                    <li className="flex items-center gap-2">
                      <div className="w-5 h-5 rounded-full bg-lightGrey border border-softGrey flex items-center justify-center text-xs">
                        3
                      </div>
                      <span>Send credentials to email</span>
                    </li>
                    <li className="flex items-center gap-2">
                      <div className="w-5 h-5 rounded-full bg-lightGrey border border-softGrey flex items-center justify-center text-xs">
                        4
                      </div>
                      <span>Save to system (only if email sent)</span>
                    </li>
                  </ol>
                </div>
              </div>
            </div>

            {/* Courses Status Info */}
            <div className="bg-lightGrey rounded-lg p-4 border border-softGrey">
              <div className="flex items-start gap-3">
                <BookOpen className="w-5 h-5 mt-0.5" style={{ color: BRAND_COLORS.darkRoyalBlue }} />
                <div>
                  <h4 className="font-medium text-darkGrey mb-1">
                    {usingDefaultCourses ? '📚 Using Default Courses' : '📋 Available Courses'}
                  </h4>
                  <p className="text-xs text-darkGrey/70">
                    {usingDefaultCourses 
                      ? '3 default courses loaded. You can add more courses from Course Management.'
                      : `${courses.length} course${courses.length !== 1 ? 's' : ''} available in system.`
                    }
                  </p>
                  {usingDefaultCourses && (
                    <Link 
                      href="/lms/Instructor_Portal/courses"
                      className="text-xs text-darkRoyalBlue hover:underline mt-2 inline-block"
                    >
                      Go to Course Management →
                    </Link>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Form Actions */}
        <div className="mt-8 pt-6 border-t border-softGrey flex justify-end gap-4">
          <Link
            href="/lms/Admin_Portal/instructors"
            className="px-6 py-3 border border-darkRoyalBlue text-darkRoyalBlue rounded-lg hover:bg-darkRoyalBlue/5 transition-colors font-medium"
          >
            Cancel
          </Link>
          <button
            type="submit"
            disabled={loading || !formData.email || !formData.name || !selectedCourseId}
            className="px-6 py-3 rounded-lg font-medium transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ 
              backgroundColor: BRAND_COLORS.deepRed,
              color: BRAND_COLORS.white 
            }}
          >
            {loading ? (
              <>
                {sendingEmail ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    Sending Credentials...
                  </>
                ) : (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    Adding Instructor...
                  </>
                )}
              </>
            ) : (
              <>
                <UserPlus className="w-5 h-5" />
                Add Instructor & Send Credentials
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  )
}